/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import InkpxWordArt11Image from 'src/assets/images/Navbar_inkpx_word_art__1__1.png';
import Image202303012246016Image from 'src/assets/images/StartupLandingPage_image_2023_03_01_224601648_removebg_preview_2.png';
import { styled } from '@mui/material/styles';
import ButtonPrimary from './ButtonPrimary';

const Navbar1 = styled('div')({
  display: `flex`,
  position: `relative`,
  flexDirection: `row`,
  width: '100%'
});

const Background = styled('div')({
  backgroundColor: `rgba(0, 118, 190, 1)`,
  width: `100%`,
  height: `5em`
});


const Image202303012246016 = styled('img')({
  objectFit: `cover`,
  height: "100%"
});


function Navbar(props) {
  return (
    <Navbar1 className={props.className}>
      <Background>
        <Image202303012246016
          src={Image202303012246016Image}
          loading="lazy"
          alt={'image_2023-03-01_224601648-removebg-preview 2'}
        />
      </Background>
    </Navbar1>
  );
}

export default Navbar;
