/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import Image5Image from 'src/assets/images/UserRegisterPagewoimage_image_5.png';
import React from 'react';
import BackgroundRemovebgPrImage from 'src/assets/images/SelectionPage_Background_removebg_preview_1.png';
import Image202303012259237Image from 'src/assets/images/SelectionPage_image_2023_03_01_225923788_removebg_preview_1.png';
import { styled } from '@mui/material/styles';
import ButtonPrimary from './ButtonPrimary';

const SelectionPage1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.3)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `100vh`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`
});

const Background = {
  backgroundColor: `rgba(0, 118, 190, 1)`,
  width: `100%`,
  height: `100vh`,
  backgroundImage: `url(${Image5Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
};

const Content = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `399px`,
  height: `371px`,
  left: `118px`,
  top: `237px`,
});

const ButtonPrimary1 = styled(ButtonPrimary)(({ theme }) => ({
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `311px`,
}));

const Title = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `3em`,
  letterSpacing: `0px`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  position: `relative`,
  margin: '0em 0em 1em 0em'
});

const BackgroundRemovebgPr = styled('img')({
  height: `575px`,
  width: `610px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `730px`,
  top: `62px`,
});

const Image202303012259237 = styled('img')({
  objectFit: `cover`,
  position: `relative`
});

const ButtonPrimary2 = styled(ButtonPrimary)(({ theme }) => ({
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `321px`,
}));


function SelectionPage(props) {
  return (
    <div style={Background}>
      <div className="container">
      <div className="row-lg-6 p-3">
        <Image202303012259237
          src={Image202303012259237Image}
          loading="lazy"
          alt={'image_2023-03-01_225923788-removebg-preview 1'}
          />
      </div>
      <div className="row">
        <div className="container col-6 p-3">
          <div className="row m-4">
            <Title>{`Wanna reach out \nto potential \ninvestors?`}</Title>
          </div>
          <div className="row p-5">
            <ButtonPrimary endPoint={'start-up-registration'} title={"Start-up"} />
          </div>
        </div>
        <div className="container col-6 p-3">
          <div className="row m-3">
            <Title style={{textAlign: "left"}}>{`Your choice: \nDonate for a \ncause or invest \nfor returns `}</Title>
          </div>
          <div className="row m-3">
            <ButtonPrimary endPoint={'user-registration'} title={"Donor/Investor"} />
          </div>
        </div>
      </div>
      </div>
    </div>
  );
}

export default SelectionPage;
